"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const mensajesController_1 = require("../controllers/mensajesController");
const auth_1 = require("../middleware/auth");
const router = (0, express_1.Router)();
const mensajesController = new mensajesController_1.MensajesController();
router.use(auth_1.authMiddleware);
router.post('/', mensajesController.sendMessage);
router.get('/recibidos', mensajesController.getReceivedMessages);
router.get('/enviados', mensajesController.getSentMessages);
router.put('/:idMensaje/leer', mensajesController.markAsRead);
exports.default = router;
